### PR TITLE
Try to match leetcode's current settings

### PR DESCRIPTION
**Pull request by c-git**

### CODE REVIEW

**Comment by Antosser** [comment]
What's the point of having `cargo-leet` as a dependency?

**Comment by c-git** [comment]
You need it when the question involves trees or linked lists. It's assumed to be a dependency by the code generator so the code won't complete if it's not there.

**Comment by c-git** [comment]
Example question that needs it https://leetcode.com/problems/add-two-numbers/description/

**Comment by Antosser** [comment]
alright

**Review by Antosser — APPROVED** [review]

**Pull request merged**
